### ISSUE TITLE
Line endings broken again

### ISSUE THREAD

**Issue by jacobrosenthal** [bchr02/node-pre-gyp-github#4]
At some point accepting my PR line endings got broken again.

It seems one solution is .gitattributes file to force LF line endings:
https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings

Other ideas?

**Comment by bchr02** [comment]
@jacobrosenthal Thanks for the link, it help me to figure it out. Apparently setting my text editor to use LF instead of CRLF was not enough because Git on windows automatically converts LF to CRLF. The solution was for me to turn this feature off like this: ```git config --global core.autocrlf false```

Any chance I can get you to test it now? Thank you!

**Comment by jacobrosenthal** [comment]
Seems good again

**Comment by bchr02** [comment]
Thanks @jacobrosenthal
